import psycopg2 as dbapi2
dsn = """dbname='dronedb' user='postgres'
         host='localhost' password='postgres'"""

connection = dbapi2.connect(dsn)
cursor = connection.cursor()

statement = """CREATE TABLE IF NOT EXISTS DRONE( ID SERIAL PRIMARY KEY,
    PHOTO VARCHAR(200) UNIQUE NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    TYPE VARCHAR(200) NOT NULL,
    WEIGHT FLOAT NOT NULL,
    HEIGHT FLOAT NOT NULL,
    LENGTH FLOAT NOT NULL,
    ENDURANCE FLOAT NOT NULL,
    AREA VARCHAR(50) NOT NULL,
    TECHNOLOGY VARCHAR(50),
    PRICE FLOAT NOT NULL
    );"""
cursor.execute(statement)
connection.commit()

statement = """ CREATE TABLE IF NOT EXISTS DISTRIBUTOR( 
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(500) NOT NULL,
    AREA VARCHAR(100) NOT NULL,
    PAYMENT_METHOD VARCHAR(20) NOT NULL,
    DELIVERY_TIME VARCHAR(20) NOT NULL,
    DRONE INTEGER REFERENCES DRONE (ID)
    );"""
cursor.execute(statement)
connection.commit()

statement = """CREATE TABLE IF NOT EXISTS COMPANY( 
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(500) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    AREA VARCHAR(100) NOT NULL,
    DRONE INTEGER REFERENCES DRONE (ID)
    );"""
cursor.execute(statement)
connection.commit()


statement = """CREATE TABLE IF NOT EXISTS ORDERS(
    ID SERIAL PRIMARY KEY,
    PRICE FLOAT NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    SHIPPED_DATE VARCHAR(50) NOT NULL,
    REQUIRED_DATE VARCHAR(50) NOT NULL,
    ORDER_DATE VARCHAR(50) NOT NULL,
    DRONE INTEGER REFERENCES DRONE (ID) 
    );"""
cursor.execute(statement)
connection.commit()


statement = """CREATE TABLE IF NOT EXISTS CUSTOMER( 
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100)  NOT NULL,
    USERNAME VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(500) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(250) NOT NULL,
    AREA VARCHAR(100),
    ORDERS INTEGER  REFERENCES ORDERS (ID)
);"""
cursor.execute(statement)
connection.commit()

statement = """CREATE TABLE IF NOT EXISTS SELLER( SELLER_ID SERIAL PRIMARY KEY,
    COMPANY_ID INTEGER REFERENCES COMPANY (ID),
    DISTRIBUTOR_ID INTEGER   REFERENCES DISTRIBUTOR (ID)
    );"""
cursor.execute(statement)
connection.commit()


cursor.close()

